### ISSUE TITLE
using for

### ISSUE THREAD

**Issue by Kowalski1337** [AlinaZakharova1997/frequency_analysis#2]
https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L12

Если ты не используешь непосредственно счетчик в цикле for, а используешь только для того, чтоб выполнить цикл n раз, то считается моветоном пробегать от 1 до n включительно, лучше от 0 до n не включительно

**Comment by AlinaZakharova1997** [comment]
т е от 0 до n-1?

**Comment by Kowalski1337** [comment]
Да, от 0 до n-1 включительно, но лучше писать от 0 до n не включительно, не знаю как это объяснить, просто так принято
