### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Kowalski1337** [AlinaZakharova1997/frequency_analysis#4]
https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L2

Это особо не имеет значение, но принято сначала указывать область include, а затем using

**Comment by AlinaZakharova1997** [comment]
include std; а потом уже using?

**Comment by Kowalski1337** [comment]
Нет, я имел в виду, сначала пишешь все что ты includишь, а потом 

using namespace std;

**Comment by AlinaZakharova1997** [comment]
хорошо
