### ISSUE TITLE
Sigsegv(should be, but c++ don't think so ¯\_(ツ)_/¯ ) + wasted variable index

### ISSUE THREAD

**Issue by Kowalski1337** [AlinaZakharova1997/frequency_analysis#5]
https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L32

В vector<char> symbols у тебя symbols.size() элементов, в цикле ты пробегаешь с 0 по symbols.size() включительно, и обращаешься в не выделенную память тут: 

https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L33

Так же в каждой итерации цикла ты увеличиваешь index на 1, таким образом у тебя в цикле все время i = index, зачем тогда вообще заводить переменную index, если можно использовать i

https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L40

И да, лучше увеличивать на 1 так: index++;

**Comment by AlinaZakharova1997** [comment]
Да, проще брать сразу переменную i. Перемудрила.
if (symbols[index] == symbols[next_index]) тут я иду с 0 до конца. Невыделенная память это как index out of range?(так на Питоне называют, во всяком случае).

**Comment by Kowalski1337** [comment]
Да, как но как правило тебе не сообщают почему у тебя программа упала ,максимум строчку скажут

**Comment by AlinaZakharova1997** [comment]
Хорошо. Я поняла.

**Comment by Kowalski1337** [comment]
Все еще в некоторых местах ты делаешь увеличение на 1 так +=1, а не ++

**Comment by Kowalski1337** [comment]
https://github.com/AlinaZakharova1997/frequency_analysis/blob/63a3c9836343adf858c53013fdaf49015fdb165a/main.cpp#L36

(((
