### ISSUE TITLE
Excess line

### ISSUE THREAD

**Issue by Kowalski1337** [AlinaZakharova1997/frequency_analysis#6]
https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L35

https://github.com/AlinaZakharova1997/frequency_analysis/blob/33279054eaa55da63c879281d6f12c14ea301e6e/main.cpp#L38

В независимости от выполнения условия условного оператора, ты увеличиваешь next_index на 1, тогда зачем писать эту строчку дважды

и еще раз лучше тогда next_index++

**Comment by AlinaZakharova1997** [comment]
Тогда можно вынести сдвиг за if else?
Я писала два раза, так я хочу сдвигать следующий индекс, а первый не трогать и сдвигать первый после того, как просдвигала следующий до конца. Я таким способом беру букву, фиксирую, а со следующей буквы сравниваю первую и так до конца и считаю сколько раз встретилась первая. Потом делаю так для второй, третьей и тд
